
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.4 EDK_MS4.81d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AUDIO_DEVICE_ID,
		XPAR_AUDIO_BASEADDR,
		XPAR_AUDIO_INTERRUPT_PRESENT,
		XPAR_AUDIO_IS_DUAL
	},
	{
		XPAR_DIP_SWITCHES_8BIT_DEVICE_ID,
		XPAR_DIP_SWITCHES_8BIT_BASEADDR,
		XPAR_DIP_SWITCHES_8BIT_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCHES_8BIT_IS_DUAL
	},
	{
		XPAR_LEDS_4BIT_DEVICE_ID,
		XPAR_LEDS_4BIT_BASEADDR,
		XPAR_LEDS_4BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_4BIT_IS_DUAL
	},
	{
		XPAR_LEDS_POSITIONS_DEVICE_ID,
		XPAR_LEDS_POSITIONS_BASEADDR,
		XPAR_LEDS_POSITIONS_INTERRUPT_PRESENT,
		XPAR_LEDS_POSITIONS_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_POSITION_DEVICE_ID,
		XPAR_PUSH_BUTTONS_POSITION_BASEADDR,
		XPAR_PUSH_BUTTONS_POSITION_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_POSITION_IS_DUAL
	}
};


