name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install flex-dev, graphviz
      run: sudo apt-get install -y libfl-dev graphviz
    - name: make
      run: cd "ForeC Compiler"; make -j; echo "FOREC_COMPILER_PATH=`pwd`" >> $GITHUB_ENV
    - name: Test
      run: cd "ForeC Compiler/test/Aborts"; make
